version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=ticket_booking_system.settings
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ticketmaster
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
